### ISSUE TITLE
Move all dependencies to dependencyManagement in the root pom

### ISSUE THREAD

**Issue by swrdfish** [swrdfish/unshop#12]
Currently the root `pom.xml` contains many of the dependencies of its child modules. This needs to be changed to dependencyManagement so that all the dependency versions are in one place. The child modules should have all the dependencies listed on their respective pom.

**Comment by swrdfish** [comment]
@indiguy I am not sure about this approach. Should we use `dependencyManagement` or should we keep dependencies of every module separate? What is a good practice?

**Comment by indiguy** [comment]
@swrdfish , the inheritance principle should be applied in this situation. If more than one child uses a particular dependency, then it should be included in <dependencyManagement> of parent pom and each child should declare that too (without version) in its own pom. The version of dependency is managed by parent.
